name:                irie
version:             0.1.0.0
github:              "jfaure/irie"
license:             BSD3
author:              "James Faure"
maintainer:          "james.faure@epitech.eu"
copyright:           "2019 James Faure"

extra-source-files:
- README.md

synopsis:            Array oriented calculus of inductive constructions
category:            Compilers

description:         Please see the README on GitHub at <https://github.com/jfaure/irie#readme>

dependencies:
- unix
- base-noprelude
- pretty-simple
- protolude
- prettyprinter
- blaze-builder
- deepseq
- binary
- primitive
- semialign
- these
- text
- vector
- vector-binary-instances
- containers
- unordered-containers
- lens
- parser-combinators
- megaparsec > 8.0
- transformers
- optparse-applicative
- bytestring
- mtl
- filepath
- directory
- haskeline
- process
# - traverse-with-class
# - llvm-hs-pure >= 9.0.0
# - llvm-hs >= 9.0.0
#
# - llvm-hs-pretty
# - array
- prettyprinter

default-extensions:
- LambdaCase
- EmptyCase
- ViewPatterns
- StandaloneDeriving
- MultiWayIf
- PartialTypeSignatures
- ScopedTypeVariables
- RankNTypes
- FlexibleContexts
- TupleSections
- ConstraintKinds
- RecursiveDo
- OverloadedStrings
- DeriveDataTypeable
- DeriveGeneric
# - TypeFamilies
# - GADTs
# - PolyKinds
# - DataKinds
#- NoImplicitPrelude

# library:
#  source-dirs:
#  - compiler/
# #   - compiler/2_Parse/
# #   - compiler/3_Core/
# #   - compiler/4_LLVM/
# # ghc-options:   -Wunused-imports
#   ghc-options:   -Wno-deprecations

ghc-options:  -Wno-deprecations -fdefer-typed-holes -Wno-typed-holes #-Wunused-imports -Wunused-binds -threaded
executables:
  irie-exe:
#   dependencies: irie
    source-dirs:
    - compiler/
    - compiler/1_Main/
    - compiler/2_Parse/
    - compiler/3_Core/
#   - compiler/4_LLVM/
    - compiler/4_Proc/
    - compiler/5_Backends/

    main:          Main.hs
    ghc-options:  -fdefer-typed-holes -Wno-typed-holes -Wunused-imports # -Wunused-binds -threaded

#tests:
#  irie-test:
#    main:                Spec.hs
#    source-dirs:         test
#    ghc-options: -threaded
#    #   dependencies: irie
